name: ItemCooldowns
version: '${project.version}'
main: me.minignomer.itemcooldowns.ItemCooldowns
api-version: '1.20'
commands:
  cooldown:
    usage: /command get/set/default pearl/trident/shield/gapple/god_apple <amount_in_seconds>
    permission: itemcooldowns.cooldown